# fly.toml app configuration file generated for bellabeansdiscordbot on 2023-08-09T18:11:11-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bellabeansdiscordbot"
primary_region = "yul"

[build]
