name: Fly Deploy
on:
  push:
    branches:
      - bella-v2
      - test

env:
  branch: ${{ steps.one.outputs.substring }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: bhowell2/github-substring-action@1.0.2
        id: get-branch
        with:
          value: ${{ github.ref }}
          index_of_str: "refs/heads/"
      - run: |
          if [[ "${{ env.branch }}" == "bella-v2" ]]; then
            echo "Configuring prod data"
            echo "FLY_API_TOKEN=${{ secrets.FLY_PROD_TOKEN }}" >> $GITHUB_ENV
            echo "FLY_APP_NAME=${{ vars.FLY_PROD_APP_NAME }}" >> $GITHUB_ENV
          elif [[ "${{ env.branch }}" == "test" ]]; then
            echo "Configuring test data"
            echo "FLY_API_TOKEN=${{ secrets.FLY_TEST_TOKEN }}" >> $GITHUB_ENV
            echo "FLY_APP_NAME=${{ vars.FLY_TEST_APP_NAME }}" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --app $FLY_APP_NAME